
language: python

matrix:
    include:
        - os: osx
          language: generic
          env: TOXENV=py32
        - os: osx
          language: generic
          env: TOXENV=py33
install:
    - ./.travis/install.sh
    - pip install ansible
    
script: 
  - ansible --version
