
language: python
cache: pip

matrix:
    include:
        - os: osx
          language: generic
          env: TOXENV=py33

install:
    - ./.travis/install.sh
    - pip install ansible
    
script: 
  - ansible --version
  - blah
  - cd $TRAVIS_BUILD_DIR/tests/01_sanity && ./start.sh
  - cd $TRAVIS_BUILD_DIR/tests/02_install_twice && ./start.sh
  - cd $TRAVIS_BUILD_DIR/tests/03_install_uninstall && ./start.sh
  - cd $TRAVIS_BUILD_DIR/tests/04_uninstall && ./start.sh
  - cd $TRAVIS_BUILD_DIR/tests/05_outputs && ./start.sh
